project:
  type: website

website:
  title: "SQL & Linear Regression"
  navbar:
    left:
      - href: index.qmd
        text: SQL Queries
      - regression.qmd
      - technology_exploration.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-expand: true

editor: visual

